AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local dev for Bruce Quotes (SAM + DynamoDB Local)

Globals:
    Function:
        Runtime: python3.12
        Architectures: [arm64]
        Timeout: 10
        MemorySize: 512

Resources:
    ApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.handler
            CodeUri: lambda/
            Events:
                Http:
                    Type: HttpApi
            Environment:
                Variables:
                    # App config
                    AWS_REGION: us-east-2
                    TABLE_NAME: bruce-quotes

                    # Point Lambda (running in SAM) at the Docker Compose service
                    DYNAMODB_ENDPOINT: http://dynamodb-local:8000

                    # Use the SAME fake creds as host so DDB Local maps to the same DB
                    AWS_ACCESS_KEY_ID: fake
                    AWS_SECRET_ACCESS_KEY: fake
