name: Expand IAM Wildcards

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  expand-wildcards:
    runs-on: ubuntu-latest
    steps:
      - name: Expand IAM Wildcards
        uses: thekbb/expand-iam-wildcards@30f10994e94960d3b05eb6eaa4fc55ee9c769714 # v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
