name: Expand IAM Wildcards

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  expand-wildcards:
    runs-on: ubuntu-latest
    steps:
      - name: Expand IAM Wildcards
        uses: thekbb/expand-iam-wildcards@02c3df30d63d4f5369171f6844c291cc32b05e33 # v1.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
