name: Expand IAM Wildcards

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  expand-wildcards:
    runs-on: ubuntu-latest
    steps:
      - name: Expand IAM Wildcards
        uses: thekbb/expand-iam-wildcards@34270469aebb92a54722a8e7a4468a46ca6fb4ca # v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
