name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.tf'
      - 'lambda/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-2

concurrency:
  group: the-one-group-to-rule-them-all
  cancel-in-progress: false

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      id-token: write  # Required for OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/bruce-quotes-github-terraform-plan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        uses: thekbb/terraform-plan-commenter-action@f26d4b3558063e7e0372bdaa5445187bc99f0fc9 # v2.0.0
        with:
          terraform-version: '1.14.3'
