name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.tf'
      - 'lambda/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-2

concurrency:
  group: the-one-group-to-rule-them-all
  cancel-in-progress: false

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      id-token: write  # Required for OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/bruce-quotes-github-terraform-plan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        uses: thekbb/terraform-plan-commenter-action@cf64d3c8071a9d4e3efcd3942b712766d9edfd26 # v2.1.1
        with:
          terraform-version: '1.14.3'
